import React from 'react';

const MandalList = ({ selectedDistrict, onMandalSelect }) => {
    // Assuming a simple mapping of districts to mandals for demonstration

    const MyStyles = {

    }
    const mandalLists = {
        'ADILABAD': ['Adilabad(M)', 'ADILABAD(URBAN)', 'BAZARHATHNOOR', 'BELA', 'BHEEMPUR', 'BOATH', 'GADIGUDA', 'GUDIHATNOOR', 'ICHODA', 'INDERAVELLY', 'JAINAD', 'MAVALA', 'NARNOOR', 'NERADIGONDA', 'SIRIKONDA', 'TALAMADUGU', 'TAMSI', 'UTNUR',],
        'BHADRADRI_KOTHAGUDEM': ['ALLAPALLI', 'ANNAPUREDDYPALLI', 'ASWAPURAM', 'ASWARAOPETA', 'BHADRACHALAM', 'BURGAMPADU', 'CHANDRUGONDA', 'CHERLA', 'CHUNCHUPALLY', 'DAMMAPETA', 'DUMMAGUDEM', 'GUNDALA', 'JULURPAD', 'KARAKAGUDEM', 'KOTHAGUDEM', 'LAXMIDEVIPALLY', 'MANUGURU', 'MULAKALAPALLE', 'PALWANCHA', 'PINAPAKA', 'SUJATHANAGAR', 'TEKULAPALLE', 'YELLANDU',],
        'HANUMAKONDA': ['ATMAKUR', 'BHEEMADEVARPALLE', 'DAMERA', 'DHARMASAGAR', 'ELKATHURTHI', 'HANAMKONDA', 'HASANPARTHY', 'INAVOLU', 'KAMALAPUR', 'KHAZIPET', 'NADIKUDA', 'PARKAL', 'SHAYAMPET', 'VELAIR',],
        'HYDERABAD': ['Nothing to show, Under the Maintenance'],
        'JAGTIAL': ['BEERPUR', 'BUGGARAM', 'DHARMAPURI', 'GOLLAPALLE', 'IBRAHIMPATNAM', 'JAGTIAL', 'JAGTIAL_RURAL', 'KODIMIAL', 'KORATLA', 'KOTHLAPUR', 'MALLAPUR', 'MALLIAL', 'MEDIPALLE', 'METPALLE', 'PEGADAPALLE', 'RAIKAL', 'SARANGAPUR', 'VELGATOOR',],
        'JANGAON': ['BACHANNAPETA', 'CHILPUR', 'DEVARUPPULA', 'GHANPUR', 'JANGAON', 'KODAKANDLA', 'LINGALA_GHANPUR', 'NARMETTA', 'PALAKURTHI', 'RAGHUNATHA_PALLE', 'THARIGOPPULA', 'ZAFFERGADH',],
        'KAMAREDDY': ['BANSWADA', 'BHIKNOOR', 'BIBIPET', 'BICHKUNDA', 'BIRKUR', 'DOMAKONDA', 'GANDHARI', 'JUKKAL', 'KAMAREDDY', 'LINGAMPET', 'MACHAREDDY', 'MADNOOR', 'NAGIREDDYPET', 'NASRULLABAD', 'NIZAMSAGAR', 'PEDDA_KODAPGAL', 'PITLAM', 'RAJAMPET', 'RAMAREDDY', 'SADASIVANAGAR', 'TADWAI', 'YELLAREDDY',],
        'KARIMNAGAR': ['CHIGURUMAMIDI', 'CHOPPADANDI', 'ELLANDAKUNTA', 'GANGADHARA', 'GANNERUVARAM', 'HUZURABAD', 'JAMMIKUNTA', 'KARIMNAGAR', 'KARIMNAGAR_RURAL', 'KOTHAPALLI', 'MANAKONDUR', 'RAMADUGU', 'SHANKARAPATNAM', 'THIMMAPUR', 'V_SAIDAPUR', 'VEENAVANKA',],
        'KHAMMAM': ['BONAKAL', 'CHINTHAKANI', 'ENKURU', 'KALLURU', 'KAMEPALLE', 'KHAMMAM_RURAL', 'KHAMMAM_URBAN', 'KONIJERLA', 'KUSUMANCHI', 'MADHIRA', 'MUDIGONDA', 'NELAKONDAPALLE', 'PENUBALLI', 'RAGHUNADHAPALEM', 'SATHUPALLE', 'SINGARENI', 'THALLADA', 'THIRUMALAYAPALEM', 'VEMSOOR', 'WYRA', 'YERRUPALEM',],
        'MAHABUBABAD': ['BAYYARAM', 'CHINNAGUDUR', 'DANTHALAPALLE', 'DORNAKAL', 'GANGARAM', 'GARLA', 'GUDUR', 'KESAMUDRAM', 'KOTHAGUDA', 'KURAVI', 'MAHABUBABAD', 'MARIPEDA', 'NARSIMHULAPET', 'NELLIKUDUR', 'PEDDAVANGARA', 'THORRUR',],
        'MAHABUBNAGAR': ['ADDAKAL', 'BALANGAR', 'BHOOTHPUR', 'CHINNA_CHINTHA_KUNTA', 'DEVARKADARA', 'GANDEED', 'HANWADA', 'JADCHERLA', 'KOILKONDA', 'MAHABUBANAGAR_URBAN', 'MAHABUBNAGAR_RURAL', 'MIDJIL', 'MOHAMMADABAD', 'MOOSAPET', 'NAWABPET', 'RAJAPUR',],
        'MANCHERIAL': ['BELLAMPALLE', 'BHEEMARAM', 'BHEEMINI', 'CHENNUR', 'DANDEPALLE', 'HAJIPUR', 'JAIPUR', 'JANNARAM', 'KANNEPALLI', 'KASIPET', 'KOTAPALLE', 'LUXETTIPET', 'MANCHERIAL', 'MANDAMARRI', 'NASPUR', 'NENNEL', 'TANDUR', 'VEMANPALLE',],
        'MEDAK': ['ALLADURG', 'CHEGUNTA', 'CHILIPCHED', 'HAVELI_GHANPUR', 'KOWDIPALLE', 'KULCHARAM', 'MANOHARABAD', 'MASAIPET', 'MEDAK', 'NARSAPUR', 'NARSINGI', 'NIZAMPET', 'PAPANNAPET', 'RAMAYAMPET', 'REGODE', 'SHANKARAMPET_A', 'SHANKARAMPET_R', 'SHIVAMPET', 'TEKMAL', 'TOOPRAN', 'YELDURTHY',],
        'MULUG': ['ETURNAGARAM', 'GOVINDARAOPET', 'KANNAIGUDEM', 'MANGAPET', 'MULUG', 'TADVAI_SAMMAKKA_SARAKKA', 'VENKATAPUR', 'VENKATAPURAM', 'WAZEED',],
        'NAGARKARNOOL': ['ACHAMPET', 'AMRABAD', 'BALMOOR', 'BIJINAPALLY', 'CHARAKONDA', 'KALWAKURTHY', 'KODAIR', 'KOLLAPUR', 'LINGAL', 'NAGARKURNOOL', 'PADARA', 'PEDDAKOTHAPALLE', 'PENTLAVELLI', 'TADOOR', 'TELKAPALLY', 'THIMMAJILPET', 'UPPUNUNTHALA', 'URKONDA', 'VANGOOR', 'VELDANDA',],
        'NALGONDA': ['ADAVIDEVULAPALLY', 'ANUMULA', 'CHANDAMPETA', 'CHANDUR', 'CHINTHA_PALLE', 'CHITYAL', 'DAMERCHERLA', 'DEVARAKONDA', 'GUNDLA_PALLE', 'GURRAMPODE', 'KANGAL', 'KATTANGUR', 'KETHEPALLY', 'KONDA_MALLEPALLY', 'MADUGULAPALLY', 'MARRI_GUDA', 'MIRYALAGUDA', 'MUNUGODE', 'NAKREKAL', 'NALGONDA', 'NAMPALLY', 'NARKETPALLE', 'NEREDUGOMMU', 'NIDAMANUR', 'PEDA_ADISHARLA_PALLI', 'PEDDAVOORA', 'SHALIGOURARAM', 'TIPPARTHY', 'TIRUMALAGIRI_SAGAR', 'TRIPURARAM', 'VEMULAPALLY',],
        'NARAYANPET': ['DAMARAGIDDA', 'DHANWADA', 'KOSGI', 'KRISHNA', 'MADDUR', 'MAGANOOR', 'MAKTHAL', 'MARIKAL', 'NARAYANPET', 'NARWA', 'UTKOOR',],
        'NIRMAL': ['BASAR', 'BHAINSA', 'DASTURABAD', 'DILAWARPUR', 'KADDAM', 'KHANAPUR', 'KUBEER', 'KUNTALA', 'LAXMANCHANDA', 'LOKESHWARAM', 'MAMADA', 'MUDHOLE', 'NARSAPUR_G', 'NIRMAL', 'NIRMAL_RURAL', 'PEMBI', 'SARANGAPUR', 'SOAN', 'TANUR',],
        'NIZAMABAD': ['ARMOOR', 'BALKONDA', 'BHEEMGAL', 'BODHAN', 'CHANDUR', 'DHARPALLY', 'DICHPALLY', 'INDALWAI', 'JAKRANPALLE', 'KAMMARPALLY', 'KOTAGIRI', 'MAKLOOR', 'MENDORA', 'MORTHAD', 'MOSRA', 'MUGPAL', 'MUPKAL', 'NANDIPET', 'NAVIPET', 'NIZAMABAD_NORTH', 'NIZAMABAD_RURAL', 'NIZAMABAD_SOUTH', 'POTHANGAL', 'RENJAL', 'RUDRUR', 'SIRKONDA', 'VAILPOOR', 'VARNI', 'YEDAPALLY', 'YERGATLA',],
        'PEDDAPALLI': ['ANTHERGAON', 'DHARMARAM', 'ELIGAID', 'JULAPALLE', 'KAMANPUR', 'MANTHANI', 'MUTHARAM_MANTHANI', 'ODELA', 'PALAKURTHY', 'PEDDAPALLE', 'RAMAGIRI', 'RAMAGUNDAM', 'SRIRAMPUR', 'SULTANABAD',],
        'RANGAREDDY': ['ABDULLAPURMET', 'AMANGAL', 'BALAPUR', 'CHEVELLA', 'CHOWDERGUDEM', 'FAROOQNAGAR', 'GANDIPET', 'HAYATHNAGAR', 'IBRAHIMPATNAM', 'KADTHAL', 'KANDUKUR', 'KESHAMPETA', 'KONDURG', 'KOTHUR', 'MADGUL', 'MAHESHWARAM', 'MANCHAL', 'MOINABAD', 'NANDIGAMA', 'RAJENDRANAGAR', 'SAROORNAGAR', 'SHABAD', 'SHAMSHABAD', 'SHANKARPALLE', 'SRILINGAMPALLE', 'TALAKONDAPALLY', 'YACHARAM',],
        'SANGAREDDY': ['AMEENPUR', 'ANDOLE', 'CHOWTAKUR', 'GUMMADIDALA', 'HATHNOOR', 'JHARASANGAM', 'JINNARAM', 'KALHER', 'KANDI', 'KANGTI', 'KOHIR', 'KONDAPUR', 'MANOOR', 'MOGUDAMPALLY', 'MUNIPALLY', 'NAGALGIDDA', 'NARAYANKHED', 'NYALKAL', 'PATANCHERU', 'PULKAL', 'RAIKODE', 'RAMACHANDRAPURAM', 'SADASIVPET', 'SANGAREDDY', 'SIRGAPOOR', 'VATPALLY', 'ZAHIRABAD',],
        'SIDDIPET': ['AKBARPET_BHOOMPALLY', 'AKKANNAPET', 'BEJJANKI', 'CHERIYAL', 'CHINNAKODUR', 'DOULTABAD', 'DUBBAK', 'GAJWEL', 'HUSNABAD', 'JAGDEVPUR', 'KOHEDA', 'KOMURAVELLI', 'KONDAPAK', 'MADDUR', 'MARKOOK', 'MIRDODDI', 'MULUGU', 'NANGANOOR', 'NARAYANRAOPET', 'RAIPOLE', 'SIDDIPET_URBAN', 'SIDDIPET_RURAL', 'THOGUTA', 'WARGAL',],
        'SURYAPET': ['ANANTHAGIRI', 'ATHMAKUR', 'CHILKUR', 'CHINTHALAPALEM_MALLAREDDYGUDEM', 'CHIVVEMLA', 'GARIDE_PALLE', 'HUZURNAGAR', 'JAJIREDDY_GUDEM', 'KODAD', 'MADDIRALA', 'MATTAMPALLE', 'MELLACHERUVU', 'MOTHEY', 'MUNAGALA', 'NADIGUDEM', 'NAGARAM', 'NEREDUCHERLA', 'NOOTHANAKAL', 'PALAKEEDU', 'PENPAHAD', 'SURYAPET', 'THIRUMALAGIRI', 'THUNGATHURTHY',],
        'VIKARABAD': ['BANTWARAM', 'BASHEERABAD', 'BOMRASPET', 'CHOWDAPUR', 'DHARUR', 'DOMA', 'DOULATABAD', 'KODANGAL', 'KOTEPALLY', 'KULKACHARLA', 'MARPALLE', 'MOMINPET', 'NAWABPET', 'PARGI', 'PEDDEMUL', 'PUDUR', 'TANDUR', 'VIKARABAD', 'YELAL',],
        'WANAPARTHY': ['AMARCHINTHA', 'ATMAKUR', 'CHINNAMBAVI', 'GHANPUR', 'GOPALPET', 'KOTHAKOTA', 'MADANAPUR', 'PANGAL', 'PEBBAIR', 'PEDDAMANDADI', 'REVALLY', 'SRIRANGAPUR', 'WANAPARTHY', 'WEEPANAGANDLA',],
        'WARANGAL': ['CHENNARAOPET', 'DUGGONDI', 'GEESUGONDA', 'KHANAPUR', 'KHILA_WARANGAL', 'NALLABELLY', 'NARSAMPET', 'NEKKONDA', 'PARVATHAGIRI', 'RAIPARTHY', 'SANGEM', 'WARANGAL', 'WARDHANNAPET',],
        'JAYASHANKAR_BHOOPALPALLY': ['BHUPALPALLY', 'CHITYAL', 'GHANAPUR_MULUG', 'KATARAM', 'KOTHAPALLYGORI', 'MAHADEVPUR', 'MALHARRAO', 'MOGULLAPALLY', 'MUTHARAM_MAHADEVPUR', 'PALIMELA', 'REGONDA', 'TEKUMATLA',],
        'JOGULAMBA_GADWAL': ['ALAMPUR', 'DHAROOR', 'GADWAL', 'GHATTU', 'IEEJA', 'ITIKYALA', 'KALOOR_TIMMANADODDI', 'MALDAKAL', 'MANOPAD', 'RAJOLI', 'UNDAVELLY', 'WADDEPALLE', 'YERRAVALLI',],
        'KOMARAM_BHEEM_ASIFABAD': ['ASIFABAD', 'BEJJUR', 'CHINTALA_MANEPALLY', 'DAHEGAON', 'JAINOOR', 'KAGAZ_NAGAR', 'KERAMERI', 'KOUTHALA', 'LINGAPUR', 'PENCHIKALPET', 'REBBANA', 'SIRPUR_T', 'SIRPUR_U', 'TIRYANI', 'WANKDI',],
        'MEDCHAL_MALKAJGIRI': ['ALWAL', 'BACHUPALLY', 'BALANAGAR', 'DUNDIGAL_GANDIMAISAMMA', 'GHATKESAR', 'KAPRA', 'KEESARA', 'KUKATPALLY', 'MALKAJGIRI', 'MEDCHAL', 'MEDIPALLY', 'MOODUCHINTALAPALLE', 'QUTHBULLAPUR', 'SHAMIRPET', 'UPPAL',],
        'RAJANNA_SIRICILLA': ['BOINPALLE', 'CHANDURTHI', 'GAMBHIRAOPET', 'ILLANTHAKUNTA', 'KONARAOPETA', 'MUSTABAD', 'RUDRANGI', 'SIRSILLA', 'THANGALLAPALLI', 'VEERNAPALLI', 'VEMULAWADA', 'VEMULAWADA_RURAL', 'YELLA_REDDI_PETA',],
        'YADADRI_BHUVANAGIRI': [],
        // Add more districts and their corresponding mandals as needed
    };
    const mandals = mandalLists[selectedDistrict] || [];
    return (
        <div style={{ display: 'flex', flexWrap: 'wrap' }}>
            <h2>List of Mandals in {selectedDistrict}</h2>
            <div style={{ display: 'flex', flexWrap: 'wrap', flexGrow: '5' }}>
                {mandals.map((mandal, index) => (
                    <div key={index} onClick={() => onMandalSelect(mandal)} style={{ border: '1px solid rgb(255, 0, 0)', margin: '10px', padding: '10px', borderRadius: '8px' }}>
                        {mandal}
                    </div>
                ))}
            </div>
        </div>
    );
};
export default MandalList;